{
  "oas": {
    "components": {
      "securitySchemes": {
        "authToken": {
          "in": "header",
          "name": "Authorization",
          "type": "apiKey"
        }
      }
    },
    "info": {
      "title": "Simple API overview",
      "version": "2.0.0"
    },
    "openapi": "3.0.0",
    "paths": {
      "/": {
        "get": {
          "operationId": "listVersionsv2",
          "responses": {
            "200": {
              "content": {
                "application/json": {
                  "examples": {
                    "foo": {
                      "value": {
                        "versions": [
                          {
                            "id": "v2.0",
                            "links": [
                              {
                                "href": "http://127.0.0.1:8774/v2/",
                                "rel": "self"
                              }
                            ],
                            "status": "CURRENT",
                            "updated": "2011-01-21T11:33:21Z"
                          },
                          {
                            "id": "v3.0",
                            "links": [
                              {
                                "href": "http://127.0.0.1:8774/v3/",
                                "rel": "self"
                              }
                            ],
                            "status": "EXPERIMENTAL",
                            "updated": "2013-07-23T11:33:21Z"
                          }
                        ]
                      }
                    }
                  }
                }
              },
              "description": "200 response"
            },
            "300": {
              "content": {
                "application/json": {
                  "examples": {
                    "foo": {
                      "value": "{\n \"versions\": [\n       {\n         \"status\": \"CURRENT\",\n         \"updated\": \"2011-01-21T11:33:21Z\",\n         \"id\": \"v2.0\",\n         \"links\": [\n             {\n                 \"href\": \"http://127.0.0.1:8774/v2/\",\n                 \"rel\": \"self\"\n             }\n         ]\n     },\n     {\n         \"status\": \"EXPERIMENTAL\",\n         \"updated\": \"2013-07-23T11:33:21Z\",\n         \"id\": \"v3.0\",\n         \"links\": [\n             {\n                 \"href\": \"http://127.0.0.1:8774/v3/\",\n                 \"rel\": \"self\"\n             }\n         ]\n     }\n ]\n}\n"
                    }
                  }
                }
              },
              "description": "300 response"
            }
          },
          "summary": "List API versions"
        }
      },
      "/v2": {
        "get": {
          "operationId": "getVersionDetailsv2",
          "responses": {
            "200": {
              "content": {
                "application/json": {
                  "examples": {
                    "foo": {
                      "value": {
                        "version": {
                          "id": "v2.0",
                          "links": [
                            {
                              "href": "http://127.0.0.1:8774/v2/",
                              "rel": "self"
                            },
                            {
                              "href": "http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf",
                              "rel": "describedby",
                              "type": "application/pdf"
                            },
                            {
                              "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                              "rel": "describedby",
                              "type": "application/vnd.sun.wadl+xml"
                            },
                            {
                              "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                              "rel": "describedby",
                              "type": "application/vnd.sun.wadl+xml"
                            }
                          ],
                          "media-types": [
                            {
                              "base": "application/xml",
                              "type": "application/vnd.openstack.compute+xml;version=2"
                            },
                            {
                              "base": "application/json",
                              "type": "application/vnd.openstack.compute+json;version=2"
                            }
                          ],
                          "status": "CURRENT",
                          "updated": "2011-01-21T11:33:21Z"
                        }
                      }
                    }
                  }
                }
              },
              "description": "200 response"
            },
            "203": {
              "content": {
                "application/json": {
                  "examples": {
                    "foo": {
                      "value": {
                        "version": {
                          "id": "v2.0",
                          "links": [
                            {
                              "href": "http://23.253.228.211:8774/v2/",
                              "rel": "self"
                            },
                            {
                              "href": "http://docs.openstack.org/api/openstack-compute/2/os-compute-devguide-2.pdf",
                              "rel": "describedby",
                              "type": "application/pdf"
                            },
                            {
                              "href": "http://docs.openstack.org/api/openstack-compute/2/wadl/os-compute-2.wadl",
                              "rel": "describedby",
                              "type": "application/vnd.sun.wadl+xml"
                            }
                          ],
                          "media-types": [
                            {
                              "base": "application/xml",
                              "type": "application/vnd.openstack.compute+xml;version=2"
                            },
                            {
                              "base": "application/json",
                              "type": "application/vnd.openstack.compute+json;version=2"
                            }
                          ],
                          "status": "CURRENT",
                          "updated": "2011-01-21T11:33:21Z"
                        }
                      }
                    }
                  }
                }
              },
              "description": "203 response"
            }
          },
          "summary": "Show API version details"
        }
      }
    },
    "security": [
      {
        "authToken": []
      }
    ],
    "servers": [
      {
        "url": "https://strategic-handball-gw.aws-euw2.cloud-ara.tyk.io/apis"
      },
      {
        "description": "local",
        "url": "http://localhost:3000"
      }
    ],
    "x-tyk-api-gateway": {
      "info": {
        "dbId": "669ed2aeab4c78000103e890",
        "id": "8fef8398b54d4adc7f4f0d208c56e92a",
        "name": "Simple API overview",
        "orgId": "664f5023d4df31000105fc8d",
        "state": {
          "active": true
        }
      },
      "middleware": {
        "global": {
          "contextVariables": {
            "enabled": true
          },
          "trafficLogs": {
            "enabled": true
          }
        },
        "operations": {
          "getVersionDetailsv2": {
            "allow": {
              "enabled": true
            }
          },
          "listVersionsv2": {
            "allow": {
              "enabled": true
            }
          }
        }
      },
      "server": {
        "authentication": {
          "enabled": true,
          "securitySchemes": {
            "authToken": {
              "enabled": true
            }
          }
        },
        "detailedActivityLogs": {
          "enabled": true
        },
        "detailedTracing": {
          "enabled": true
        },
        "gatewayTags": {
          "enabled": true,
          "tags": [
            "edge",
            "aws-eu-west-2"
          ]
        },
        "listenPath": {
          "strip": true,
          "value": "/apis"
        }
      },
      "upstream": {
        "url": "http://localhost:3000"
      }
    }
  },
  "categories": [
    "test"
  ],
  "hook_references": [],
  "is_site": false,
  "sort_by": 0,
  "user_group_owners": [],
  "user_owners": []
}